"""
Built-in training presets. Each returns a partial dict that overrides defaults.
"""
from __future__ import annotations

PRESETS = {
    "SDXL Character": {
        "model_type": "SDXL",
        "network_type": "lora",
        "rank": 32,
        "alpha": 16.0,
        "learning_rate": 1e-4,
        "text_encoder_lr": 5e-5,
        "text_encoder_training": False,
        "optimizer": "AdamW8bit",
        "lr_scheduler": "cosine",
        "batch_size": 1,
        "epochs": 20,
        "resolution": 1024,
        "cache_latents": True,
        "gradient_checkpointing": True,
        "mixed_precision": "bf16",
        "gradient_clip_norm": 1.0,
        "noise_offset": 0.0,
        "loss_function": "mse",
    },
    "SDXL Style": {
        "model_type": "SDXL",
        "network_type": "lora",
        "rank": 64,
        "alpha": 32.0,
        "learning_rate": 5e-5,
        "text_encoder_lr": 1e-5,
        "text_encoder_training": True,
        "optimizer": "AdamW8bit",
        "lr_scheduler": "cosine",
        "batch_size": 1,
        "epochs": 30,
        "resolution": 1024,
        "cache_latents": False,
        "gradient_checkpointing": True,
        "mixed_precision": "bf16",
        "noise_offset": 0.05,
        "loss_function": "mse",
    },
    "SDXL Concept": {
        "model_type": "SDXL",
        "network_type": "lora",
        "rank": 16,
        "alpha": 8.0,
        "learning_rate": 2e-4,
        "text_encoder_lr": 5e-5,
        "text_encoder_training": False,
        "optimizer": "Prodigy",
        "lr_scheduler": "constant",
        "batch_size": 1,
        "epochs": 15,
        "resolution": 1024,
        "cache_latents": True,
        "gradient_checkpointing": True,
        "mixed_precision": "bf16",
    },
    "Flux Character": {
        "model_type": "Flux Dev",
        "network_type": "lora",
        "rank": 16,
        "alpha": 8.0,
        "learning_rate": 1e-4,
        "text_encoder_lr": 5e-5,
        "text_encoder_training": False,
        "optimizer": "AdamW8bit",
        "lr_scheduler": "cosine",
        "batch_size": 1,
        "epochs": 20,
        "resolution": 768,
        "cache_latents": True,
        "gradient_checkpointing": True,
        "mixed_precision": "bf16",
        "quantization": "nf4",
    },
    "Flux Style": {
        "model_type": "Flux Dev",
        "network_type": "lora",
        "rank": 32,
        "alpha": 16.0,
        "learning_rate": 5e-5,
        "text_encoder_lr": 1e-5,
        "text_encoder_training": False,
        "optimizer": "AdamW8bit",
        "lr_scheduler": "cosine",
        "batch_size": 1,
        "epochs": 30,
        "resolution": 512,
        "cache_latents": True,
        "gradient_checkpointing": True,
        "mixed_precision": "bf16",
        "quantization": "nf4",
    },
    "Low VRAM (12GB)": {
        "resolution": 512,
        "batch_size": 1,
        "cache_latents": True,
        "gradient_checkpointing": True,
        "quantization": "nf4",
        "mixed_precision": "bf16",
        "optimizer": "AdamW8bit",
        "grad_accum_steps": 4,
    },
    "Balanced": {
        "network_type": "lora",
        "rank": 32,
        "alpha": 16.0,
        "learning_rate": 1e-4,
        "optimizer": "AdamW8bit",
        "lr_scheduler": "cosine",
        "batch_size": 1,
        "epochs": 20,
        "cache_latents": True,
        "gradient_checkpointing": True,
        "mixed_precision": "bf16",
        "gradient_clip_norm": 1.0,
    },
    "High Quality": {
        "network_type": "lora",
        "rank": 64,
        "alpha": 32.0,
        "learning_rate": 5e-5,
        "text_encoder_training": True,
        "optimizer": "AdamW8bit",
        "lr_scheduler": "cosine_with_warmup",
        "warmup_ratio": 0.1,
        "batch_size": 1,
        "epochs": 40,
        "cache_latents": False,
        "gradient_checkpointing": True,
        "mixed_precision": "bf16",
        "gradient_clip_norm": 1.0,
        "noise_offset": 0.03,
        "min_snr_gamma": 5.0,
    },
}


def get_preset_names() -> list[str]:
    return list(PRESETS.keys())


def get_preset(name: str) -> dict:
    return PRESETS.get(name, {}).copy()
